server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer_route
          uri: http://customermanagement:8081/
          predicates:
            - Path=/api/v1/customers/**
        - id: vehicle_route
          uri: http://vehiclemanagement:8082/
          predicates:
            - Path=/api/v1/vehicles/**
        - id: payment_route
          uri: http://paymentprocessing:8083/
          predicates:
            - Path=/api/v1/payments/**
        - id: rental_route
          uri: http://rentalmanagement:8084/
          predicates:
            - Path=/api/v1/rentals/**
        - id: reservation_route
          uri: http://reservationmanagement:8085/
          predicates:
            - Path=/api/v1/reservations/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

